### ISSUE TITLE
Provide pattern synonyms to access internal representations.

### ISSUE THREAD

**Issue by Skyb0rg007** [minad/writer-cps-transformers#10]
The current `transformers`  (0.5.6.2) does not expose the internal representations of `Control.Monad.Trans.Writer.CPS` or `Control.Monad.Trans.RWS.CPS`. This makes it impossible to implement certain things, ex. `MFunctor` from the `mmorph` package. The `transformers` package has had an ongoing issue for [about a year](https://hub.darcs.net/ross/transformers/issue/67), but even in the case of an update, some packages may want to maintain backward-compatibility.

In version 0.5.5.0, this package exported the modules `Control.Monad.Trans.Writer.CPS.Internal` and `Control.Monad.Trans.RWS.CPS.Internal`, which exposed these representations.
My proposal is to re-add these modules, exporting the original interface with the addition of the following pattern synonyms:

```
{-# LANGUAGE PatternSynonyms, ViewPatterns #-}

pattern WriterT :: (w -> m (a, w)) -> WriterT w m a
pattern WriterT x = (unsafeCoerce -> x)
    where WriterT x = unsafeCoerce x
{-# COMPLETE WriterT #-}

pattern RWST :: (r -> s -> w -> m (a, s, w)) -> WriterT w m a
pattern RWST x = (unsafeCoerce -> x)
    where RWST x = unsafeCoerce x
{-# COMPLETE RWST #-}
```
Because these datatypes are implemented via `newtype`, this usage of `unsafeCoerce` is [safe with `ghc`](http://hackage.haskell.org/package/base-4.14.0.0/docs/GHC-Exts.html#v:unsafeCoerce-35-). 

This allows for implementation of `MFunctor`:

```
instance MFunctor (WriterT w) where
    hoist :: Monad m => (forall a. m a -> n a) -> WriterT w m b -> WriterT w n b
    hoist nat (WriterT m) = WriterT $ \w -> nat (m w)
```

**Comment by minad** [comment]
No, this should be fixed upstream in transformers.
