### ISSUE TITLE
Create Control.Lens instances

### ISSUE THREAD

**Issue by louispan** [minad/writer-cps-transformers#3]
https://github.com/louispan/writer-cps-lens can be used once the Internal module code is merged.

**Comment by minad** [comment]
Hi,

why do you need these isos for Lazy? Is there some use case? Maybe one could just assume that lazy writers won't be used at all... 

Am 17. Januar 2017 13:11:54 MEZ, schrieb louispan <notifications@github.com>:

**Comment by louispan** [comment]
Good point. It's probably not very useful. I'll remove the Strict instance and the LazyXXXT wrappers.

**Comment by minad** [comment]
It is probably better to add it if a use case comes up as you wrote. Also the adhoc newtype wrapper makes this even more artifical.

**Comment by louispan** [comment]
Hi Daniel,

Travis is passing for the lens instances package. Do you want to own this
repo and maintain this package or shall I upload it to hackage?

**Comment by minad** [comment]
Hi Louis,

you should upload it. If you want you could add me as a maintainer? I can also add you to the transformer packages if you are interested in using those in the future (it seems you want to depend on them in your glazier project?)

Daniel

Am 18. Januar 2017 08:35:57 MEZ, schrieb louispan <notifications@github.com>:

**Comment by louispan** [comment]
Hi Daniel,

Okay, I'll add you as a maintainer of writer-cps-lens. I don't think I'll
need to be a maintainer of the transformers package just now - I'll ask
again if I find another missing use case.

Yes, I'll like to use your RWST in my glazier project. I'm experimenting
with using it to creating composable widgets.

It's still very early days, I keep making breaking changes, but I'll let
you know if I get anywhere useful!

Cheers,

Louis
