### ISSUE TITLE
Do not provide liftCallCC'

### ISSUE THREAD

**Issue by int-index** [minad/writer-cps-transformers#5]
The fact that this implementation of `Writer` is under the hood a `State` shouldn't show up in the public interface.

In particular, there shouldn't be a `liftCallCC'` function in the public module. Only `liftCallCC` should be provided and it should behave like the one for `Writer`, not like the one for `State`.

**Comment by int-index** [comment]
The lack of discipline around this issue causes this bug:

```
module WriterCPS where

import Data.Monoid
import Control.Monad.Cont
import Control.Monad.Writer.Class
import Control.Monad.State.Class

import qualified Control.Monad.RWS.Strict as S
import qualified Control.Monad.RWS.CPS    as CPS

fm :: (MonadCont m, MonadState Bool m, MonadWriter String m) => m ()
fm = do
  tell "outside;"
  callCC $ \cont -> do
    put False
    tell "inside;"
    cont ()

f :: ((), Bool, String)
f = runCont (S.runRWST fm () True) id

g :: ((), Bool, String)
g = runCont (CPS.runRWST fm () True) id
```

Here, `f = ((),False,"outside;")` and `g = ((),True,"outside;inside;")`, which clearly means that `RWST` from this package isn't a drop-in replacement for the regular `RWST`.

**Comment by minad** [comment]
Right! I hope there are not too many other inconsistencies. There are some concerning the places where Monoid constraints are needed however.

Can you create a PR concerning liftCallCC?

**Comment by minad** [comment]
@int-index Clearly this is a bug, this should act as a drop-in replacement. If you find more please let me know!

**Comment by int-index** [comment]
@minad Alright, I opened two PRs (one to this repo and one to `writer-cps-mtl`) that together seem to fix the issue.

I haven't written a formal proof that my changes are correct, but I added a test suite.

**Comment by minad** [comment]
Thank you very much!

About a test suite, the situation is very bad. There is also no test-suite for transformers :-/
We should probably write one for everything...

**Comment by minad** [comment]
@int-index Do you need a new release or should I wait a few days, just in case that you find some more issues?

**Comment by int-index** [comment]
I've discovered this issue while working on a new https://hackage.haskell.org/package/transformers-lift release. I don't think I'll find more any time soon.

**Comment by minad** [comment]
Ok, I make a new release then. I though you might find more in the light of https://github.com/ekmett/mtl/issues/38
