### ISSUE TITLE
Make this package a compatibility package for older transformers

### ISSUE THREAD

**Issue by minad** [minad/writer-cps-transformers#7]
See https://hub.darcs.net/ross/transformers/patch/b6743fad9f5ce8a9e13f15320f7d2752330084e2

**Comment by minad** [comment]
@hvr Does it make sense to push these two versions to hackage to fix the name conflict with the transformers package? From version 0.5.6.0 on, this package does nothing and the transformer modules are used instead.

0.5.4: https://github.com/minad/writer-cps-transformers/commit/52445ee30ddf9c19bfbb8e911324d5890b061a2b
0.5.6: https://github.com/minad/writer-cps-transformers/commit/a8b01d97ab3945264caa7585e4e15149a89fe9af

**Comment by snoyberg** [comment]
See also #8, which uses a different approach (conditional flags) to hide the modules when using a newer version of the transformers package.

**Comment by snoyberg** [comment]
Never mind, scratch that. Your existing approach makes sense, I'll close the PR.

**Comment by minad** [comment]
@snoyberg Thanks. I will probably push these one soon to hackage. Then I will update the version bounds for all the other writer-cps-* packages such that they will use the new transformer package if available.

**Comment by minad** [comment]
There is only one issue though - the transformer packages doesn't expose the Internal modules which are used by some downstream packages (e.g. https://github.com/int-index/transformers-lift/issues/7). Hopefully the transformer package will expose them in some newer version.

**Comment by snoyberg** [comment]
I don't have a strong opinion here. I think I originally foresaw a problem with the approach you had here (which is why I started the PR), but I don't remember what it was. There's some functionality in newer versions of Cabal that I've never used which allows reexporting modules. An example is @hvr's base-noprelude package:

https://hackage.haskell.org/package/base-noprelude-4.12.0.0/base-noprelude.cabal

Since @hvr both wrote that package and is more closely involved in Cabal, he can probably give a better recommendation than I can on whether it's an approach worth using here.

**Comment by snoyberg** [comment]
> There is only one issue though - the transformer packages doesn't expose the Internal modules which are used by some downstream packages (e.g. int-index/transformers-lift#7). Hopefully the transformer package will expose them in some newer version.

This leaves you caught between a rock and a hard place. You can't reexport the same interface you had previously, so downstream _will_ be broken. Or you can continue with the existing data types and have incompatibility with the types in transformers. There's no good answer here, sorry :(

**Comment by minad** [comment]
Yes, for that Internal issue there is no good solution. There is already a bug filed for the transformers package by  @int-index, see https://hub.darcs.net/ross/transformers/issue/67
